"""transfer and balance.

Revision ID: 247c145ab2b9
Revises: e88984445d17
Create Date: 2022-01-08 22:17:18.568137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247c145ab2b9'
down_revision = 'e88984445d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=80), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['token_contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=False),
    sa.Column('to_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=80), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.Numeric(precision=80), nullable=False),
    sa.Column('signature_r', sa.Numeric(precision=80), nullable=True),
    sa.Column('signature_s', sa.Numeric(precision=80), nullable=True),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['token_contract.id'], ),
    sa.ForeignKeyConstraint(['from_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer')
    op.drop_table('balance')
    # ### end Alembic commands ###
