"""unique balance.

Revision ID: 823ccd1a47db
Revises: 247c145ab2b9
Create Date: 2022-01-09 02:10:50.208327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823ccd1a47db'
down_revision = '247c145ab2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'balance', ['account_id', 'contract_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('balance_account_id_contract_id_key', 'balance', type_='unique')
    # ### end Alembic commands ###
