"""calldata cleanup.

Revision ID: 8456fc430218
Revises: 8e5f0c5e530f
Create Date: 2022-03-13 00:37:19.914768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8456fc430218'
down_revision = '8e5f0c5e530f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'calldata')
    op.alter_column('block', '_document', type_=postgresql.JSONB())
    op.drop_constraint('token_flow_transaction_id_key', 'token_flow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('calldata', sa.JSON()))
    op.execute("""
    UPDATE transaction tx SET calldata = b._document->'transactions'->tx.transaction_index->
    CASE WHEN tx.type != 'DEPLOY' THEN 'calldata' ELSE 'constructor_calldata' END
    FROM block b WHERE tx.block_number = b.id;
    """)
    op.alter_column('transaction', 'calldata', nullable=False)
    op.alter_column('block', '_document', type_=sa.JSON())
    op.create_unique_constraint(None, 'token_flow', ['transaction_id'])
    # ### end Alembic commands ###
