"""token flow extra, a

Revision ID: 8e5f0c5e530f
Revises: 9a8f2f07bfaf
Create Date: 2022-03-11 14:14:48.253935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e5f0c5e530f'
down_revision = '9a8f2f07bfaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_flow', sa.Column('extra', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_flow', 'extra')
    # ### end Alembic commands ###
