"""limit order loader, the.

Revision ID: 9a8f2f07bfaf
Revises: 3bdecf573d73
Create Date: 2022-03-02 14:41:15.777352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8f2f07bfaf'
down_revision = '3bdecf573d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('limit_order_load',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('tx_hash2', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['limit_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash'),
    sa.UniqueConstraint('tx_hash2')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('limit_order_load')
    # ### end Alembic commands ###
