"""balance loader, the.

Revision ID: 9e325ee78ee9
Revises: f6d5a12e41c4
Create Date: 2022-03-02 12:47:17.526078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e325ee78ee9'
down_revision = 'f6d5a12e41c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_load',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance_id', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['balance_id'], ['balance.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('balance_id'),
    sa.UniqueConstraint('tx_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance_load')
    # ### end Alembic commands ###
