"""deposit and withdrawal, the.

Revision ID: f0a9874867fc
Revises: 823ccd1a47db
Create Date: 2022-02-08 23:27:24.461176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a9874867fc'
down_revision = '823ccd1a47db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=True),
    sa.Column('to_account_id', sa.Integer(), nullable=True),
    sa.Column('_address', sa.String(), nullable=True),
    sa.Column('nonce', sa.Numeric(precision=80), nullable=True),
    sa.ForeignKeyConstraint(['from_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('deposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('balance_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=80), nullable=False),
    sa.ForeignKeyConstraint(['balance_id'], ['balance.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('withdrawal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('balance_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=80), nullable=False),
    sa.Column('_address', sa.String(), nullable=False),
    sa.Column('nonce', sa.Numeric(precision=80), nullable=False),
    sa.ForeignKeyConstraint(['balance_id'], ['balance.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawal')
    op.drop_table('deposit')
    op.drop_table('token_flow')
    # ### end Alembic commands ###
